### ISSUE TITLE
Compilation error after updating sttp lib or ZIO 2

### ISSUE THREAD

**Issue by pawank** [lewapek/observability-demo-apps#1]
Hi,

First, thank you for putting the config and how-to for using zio-opentelenetry with a complete example. 
Its works great with the existing configured library versions but as soon as either sttp is updated to 3.10.2 or ZIO to zio 2.1.0 (working till zio 2.0.22)
Compilation error after lib upgrades
![error1_sttp_3 10 2](https://github.com/user-attachments/assets/33de736b-9efc-40fe-8ac5-e3ca4b43aca1)

The following changes were tried as per https://github.com/zio/zio/pull/8612 
Using `type SttpBackendType = SttpBackend[Task, Any]` 

Do you have any suggestions to make it work with sttp 3.10.2 and ZIO 2.1.14.

**Comment by lewapek** [comment]
Hi,
try below snippet with manually created tag:

```
  // below 2 lines fix compilation problem with sttp backend below
  type ZIOStreamsWebsockets = ZioStreams & WebSockets
  given sttpClientTag: Tag[SttpBackend[Task, ZIOStreamsWebsockets]] =
    Tag.materialize[SttpBackend[Task, ZIOStreamsWebsockets]]
  lazy val sttpBackendLayer: ZLayer[Any, Throwable, SttpBackend[Task, ZIOStreamsWebsockets]] =
    ZLayer.scoped(
      HttpClientZioBackend
        .scoped()
        .map(delegate => LoggingBackend(delegate, ZIOSttpLogger, logResponseBody = true, logResponseHeaders = true))
    )
 ```

**Comment by pawank** [comment]
Working with your suggestions.
